#!/usr/bin/python3
"""
Module documentation - defines empty class
"""


class BaseGeometry():
    """
    BaseGeometry defined with module of area
    """

    def __init__area(self):
        """
        define area with out any implementation
        """

        raise NotImplementedError("area() is not implemented")

    def __init__integer_validator(self, name, value):
        """
        returns the valueeror and typeerror
        """

        self.name = name
        self.value = value
        if not isinstance(self.value, int):
            raise TypeError(f"{name} must be an integer")
        if self.value <= 0:
            raise ValueError("{name} must be greater than 0")
